name: WauzDiscord
description: Advanced Minecraft MMORPG Engine - Discord Addon
main: eu.wauz.wauzdiscord.WauzDiscord
website: http://wauz.eu/
version: 1.0
api-version: 1.16
author: Nikolas Keller
depend: [WauzCore]
commands:
  discord:
    description: Send Message in Discord
    usage: /discord [text]
    permission: wauz.system