name: WauzStarter
description: Advanced Minecraft MMORPG Engine - Startup Module
main: eu.wauz.wauzstarter.WauzStarter
website: http://wauz.eu/
version: 1.0
api-version: 1.16
author: Nikolas Keller
loadbefore: [MythicMobs, WauzCore]